name: Package for scaleway

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag rg.fr-par.scw.cloud/theolemoine/mamie-danger
      - name: Login to scaleway
        run: docker login rg.fr-par.scw.cloud/theolemoine -u nologin -p $SCW_SECRET_TOKEN
        env:
          SCW_SECRET_TOKEN: ${{ secrets.SCW_SECRET_TOKEN }}
      - name: Push to scaleway
        run: docker push rg.fr-par.scw.cloud/theolemoine/mamie-danger
